// ── tests/naryad_566_plan_summary_numbers.rs ─────────────────────────
// №566 (Wave 25 P2 tail; the audit 02.10 §7.2 W-4; dispatch gh#925):
// the public digest (docs/PLAN-SUMMARY.md) carries a hand-written
// "now 2110 bp" while the machine fact was 3195 bp — the grantors'
// digest lagged the metrics. The fix: the digest's CURRENT numbers are
// GENERATED by scripts/gen_metrics.py (the same sources as the README
// metrics block — one SSOT), and THIS test pins the two sides together:
//
//   1. the digest's generated block == an INDEPENDENT recomputation
//      from src/builtins/registry.rs (the exact regex contract of
//      scripts/ci/type_signature_share.py — the floor's own counter);
//   2. the generator's --check (which verifies BOTH targets) passes
//      right now — the generator and the committed files agree;
//   3. the audit's exact stale claim ("now 2110 bp") is gone (the
//      historical wave-23 row "floor 998→2110 bp" is a frozen snapshot
//      and stays — the Block-3 invariant: history is not a claim).
//
// №475's fs_gate ratchet targets PRODUCTION I/O paths; this file reads
// the digest and spawns the generator gate BY DESIGN — the scoped allow
// mirrors the n563 debt-counter / readme_consistency posture.
#![allow(clippy::disallowed_methods)]

use regex::Regex;
use std::collections::HashMap;
use std::fs;
use std::process::Command;

fn repo_root() -> std::path::PathBuf {
    std::path::PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR should be set by cargo"),
    )
}

/// The type_signature_share.py contract, verbatim: total = the count of
/// `spec!("name"` rows; typed = the UNIQUE names carrying a signature
/// string; precise = the bare scalar set {String, Float, Bool, Unit}.
/// bp = (n * 10000) // total — integer-exact, no float drift.
fn recompute_floor() -> (usize, usize, usize, usize, usize) {
    let path = repo_root().join("src").join("builtins").join("registry.rs");
    let content =
        fs::read_to_string(&path).unwrap_or_else(|e| panic!("cannot read {:?}: {}", path, e));

    let spec_re = Regex::new(r#"spec!\("([a-z_0-9]+)""#).unwrap();
    let typed_re = Regex::new(
        r#"spec!\("([a-z_0-9]+)",[^\n;]*;\s*[A-Za-z_0-9]+\s*,\s*"([A-Za-z][A-Za-z0-9<>{}:,_]*)"\s*\)"#,
    )
    .unwrap();

    let n_total = spec_re.captures_iter(&content).count();
    let mut typed: HashMap<String, String> = HashMap::new();
    for cap in typed_re.captures_iter(&content) {
        typed.insert(
            cap.get(1).unwrap().as_str().to_string(),
            cap.get(2).unwrap().as_str().to_string(),
        );
    }
    let n_typed = typed.len();
    let precise_types = ["String", "Float", "Bool", "Unit"];
    let n_precise = typed
        .values()
        .filter(|t| precise_types.contains(&t.as_str()))
        .count();

    let typed_bp = (n_typed * 10000).checked_div(n_total).unwrap_or(0);
    let precise_bp = (n_precise * 10000).checked_div(n_total).unwrap_or(0);
    (n_total, n_typed, typed_bp, n_precise, precise_bp)
}

fn plan_summary() -> String {
    let path = repo_root().join("docs").join("PLAN-SUMMARY.md");
    fs::read_to_string(&path).unwrap_or_else(|e| panic!("cannot read {:?}: {}", path, e))
}

#[test]
fn n566_generated_block_matches_the_independent_recomputation() {
    let (n_total, n_typed, typed_bp, n_precise, precise_bp) = recompute_floor();
    assert!(n_total > 0, "the registry must carry spec! rows");
    assert!(
        n_typed > n_precise,
        "the precise set is a subset of the typed set (the bare List/Struct rows are coarse)"
    );

    let text = plan_summary();
    let begin = text
        .find("<!-- BEGIN GENERATED NUMBERS")
        .expect("the digest must carry the BEGIN GENERATED NUMBERS marker (№566)");
    let end = text
        .find("<!-- END GENERATED NUMBERS -->")
        .expect("the digest must carry the END GENERATED NUMBERS marker (№566)");
    let block = &text[begin..end];
    assert_eq!(
        text[begin..]
            .matches("<!-- BEGIN GENERATED NUMBERS")
            .count(),
        1,
        "exactly ONE generated block in the digest"
    );

    // The floor row: "<typed_bp> bp — <typed>/<total> = <share>% (precise
    // <precise>/<total> = <precise_share>%, №560)" — every number from
    // the independent recomputation.
    let floor_row = block
        .lines()
        .find(|l| l.contains("Typed-signature floor"))
        .expect("the generated block must carry the typed-signature floor row");
    let expected = format!(
        "| {} bp — {}/{} = {:.2}% (precise {}/{} = {:.2}%, №560) |",
        typed_bp,
        n_typed,
        n_total,
        typed_bp as f64 / 100.0,
        n_precise,
        n_total,
        precise_bp as f64 / 100.0,
    );
    assert!(
        floor_row.contains(&expected),
        "the digest floor row must equal the recomputation (№566: numbers == gen_metrics.py output).\n  row:      {}\n  expected: {}",
        floor_row.trim(),
        expected
    );

    // The registry-rows row agrees with the total.
    let rows_row = block
        .lines()
        .find(|l| l.contains("BUILTIN_REGISTRY rows"))
        .expect("the generated block must carry the registry-rows row");
    assert!(
        rows_row.contains(&format!("| {} |", n_total)),
        "the registry-rows row must equal the recomputed total, got: {}",
        rows_row.trim()
    );
}

#[test]
fn n566_generator_check_is_green_right_now() {
    // The generator verifies BOTH targets (README + the digest) against
    // the repository; the CI image carries python3 (the №563
    // debt-counter precedent runs it the same way).
    let out = Command::new("python3")
        .arg("scripts/gen_metrics.py")
        .arg("--check")
        .output()
        .expect("python3 must exist (the CI image runs the gate scripts)");
    assert!(
        out.status.success(),
        "gen_metrics.py --check must pass (the generated blocks match the repo), stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
}

#[test]
fn n566_the_audit_stale_claim_is_gone() {
    let text = plan_summary();
    // The audit's exact finding: the CURRENT-wave section claimed
    // "now 2110 bp" while the fact was 3195. The hand-written current
    // number is gone (the generated block replaces it; the historical
    // wave-23 snapshot "floor 998→2110 bp" is NOT a current claim and
    // stays — the Block-3 invariant).
    assert!(
        !text.contains("now 2110 bp"),
        "the stale hand-written current claim must not return — the generated block is the SSOT (№566)"
    );
    let (_total, _typed, typed_bp, _precise, _precise_bp) = recompute_floor();
    assert!(
        text.contains(&format!("{} bp", typed_bp)),
        "the live floor ({} bp) must be present in the digest",
        typed_bp
    );
}
