#!/usr/bin/env python3
"""№462: count the builtin names specially handled by BOTH backends (TW ∩ VM).

Heuristic (documented, checked-in, reproducible):
  1. The SSOT of builtin names is BUILTIN_REGISTRY (src/builtins/registry.rs,
     `spec!("name", ...)` entries) — 500 names.
  2. A name is "handled" by a backend when the name appears as a string
     literal in that backend's code, outside line comments:
       - VM:  src/vm.rs
       - TW:  src/interpreter/*.rs
  3. The duplicated set = handled(VM) ∩ handled(TW).

The audit 25.09 (§4.1) reported 50/62/48 with a narrower match-arm regex;
its exact numbers are not reproducible from the stated heuristic (a literal
match-arm regex yields 13/5/0 — see the baseline header). This counter is
the checked-in fact: fewer false negatives (every code literal counts), the
baseline is generated by THIS script, and the CI threshold = the generated
fact, moving ONLY downward (№466's per-group transfers lower it).

Usage:
  count_duplicated_names.py                 → prints the count
  count_duplicated_names.py --list          → sorted names, one per line
  count_duplicated_names.py --artifact      → grouped sorted list (the artifact)
  count_duplicated_names.py --gate BASELINE → exit 1 if count > baseline threshold
  count_duplicated_names.py --quorum [BASELINE] → machine-readable quorum record
            (№525): quorum_num = the number of groups still carrying >= 1
            duplicated name; quorum_den = the transfer-start group total,
            machine-parsed from the baseline header's group history and
            cross-checked against its 'groups_at_transfer_start' marker.
"""
import glob
import re
import sys

ROOT = __file__.rsplit('/scripts/ci/', 1)[0]
REGISTRY = ROOT + '/src/builtins/registry.rs'
VM = ROOT + '/src/vm.rs'
TW_GLOB = ROOT + '/src/interpreter/*.rs'

NAME_RE = re.compile(r'"([a-z_][a-z_0-9]{3,})"')
SPEC_RE = re.compile(r'spec!\("([a-z_0-9]+)"')

# Preliminary group marking for the №465/№466 prioritization artifact.
GROUPS = [
    ('memory', ('memorize', 'forget', 'recall', 'memory')),
    ('db', ('db_', 'query')),
    ('sessions', ('conv_', 'session')),
    ('reflex', ('reflex_',)),
    ('media', ('media_', 'vision_')),
]


def strip_line_comments(text: str) -> str:
    return re.sub(r'//[^\n]*', '', text)


def registry_names() -> set:
    text = open(REGISTRY, encoding='utf-8').read()
    return set(SPEC_RE.findall(text))


def literals(path_glob: str) -> set:
    names = set()
    for path in sorted(glob.glob(path_glob)):
        text = strip_line_comments(open(path, encoding='utf-8').read())
        names.update(NAME_RE.findall(text))
    return names


def duplicated() -> set:
    reg = registry_names()
    vm = literals(VM) & reg
    tw = literals(TW_GLOB) & reg
    return vm & tw


def group_of(name: str) -> str:
    for label, prefixes in GROUPS:
        if any(name.startswith(p) or name == p for p in prefixes):
            return label
    return 'other'


def main() -> None:
    dups = duplicated()
    args = sys.argv[1:]
    if '--list' in args:
        print('\n'.join(sorted(dups)))
        return
    if '--artifact' in args:
        by_group = {}
        for name in sorted(dups):
            by_group.setdefault(group_of(name), []).append(name)
        print(f'duplicated builtin names TW∩VM: {len(dups)}')
        for label in sorted(by_group):
            print(f'\n[{label}] ({len(by_group[label])})')
            for name in by_group[label]:
                print(f'  {name}')
        return
    if '--quorum' in args:
        baseline = args[args.index('--baseline') + 1] \
            if '--baseline' in args else ROOT + '/scripts/ci/tw_vm_dup_names_baseline.txt'
        # num: the live groups still carrying >= 1 duplicated name
        # (the counter's own GROUPS classification + 'other').
        by_group = {}
        for name in dups:
            by_group.setdefault(group_of(name), []).append(name)
        quorum_num = len(by_group)
        # den: the transfer-start group total, machine-parsed from the
        # baseline history — every '№466 ... group K' entry plus the
        # '№483 ... FINAL group' entry — cross-checked against the
        # machine-readable marker line in the same header.
        marker = None
        entries = 0
        for line in open(baseline, encoding='utf-8'):
            m = re.match(r'#\s*groups_at_transfer_start:\s*(\d+)', line)
            if m:
                marker = int(m.group(1))
            # the group history lives on DATED entry lines only — the
            # marker comment itself must not self-match
            if not re.match(r'#\s*20\d\d-\d\d-\d\d\s', line):
                continue
            if re.search(r'№466[ \t]*\([^)]*\)[ \t]*group \d+', line) or (
                    '№483' in line and 'FINAL group' in line):
                entries += 1
        if marker is None:
            print('::error::baseline fixture has no "# groups_at_transfer_start: N" marker')
            sys.exit(2)
        if marker != entries:
            print(f'::error::the baseline quorum record is inconsistent: the marker says '
                  f'{marker} groups, the counted history entries are {entries}')
            sys.exit(2)
        print(f'quorum_num: {quorum_num}')
        print(f'quorum_den: {marker}')
        print(f'quorum groups carrying duplicates today: {quorum_num}/{marker}')
        return
    if '--gate' in args:
        baseline = args[args.index('--gate') + 1]
        threshold = None
        for line in open(baseline, encoding='utf-8'):
            m = re.match(r'#\s*threshold:\s*(\d+)', line)
            if m:
                threshold = int(m.group(1))
                break
        if threshold is None:
            print('::error::baseline fixture has no "# threshold: N" line')
            sys.exit(2)
        count = len(dups)
        print(f'tw-vm duplicated builtin names: {count} (threshold {threshold})')
        if count > threshold:
            known = {
                line.strip()
                for line in open(baseline, encoding='utf-8')
                if line.strip() and not line.startswith('#')
            }
            fresh = sorted(dups - known)
            print(
                f'::error::the TW/VM duplicate-name count grew {threshold} → {count} '
                f'(ADR-0177 §4 criterion 2: the threshold moves ONLY down). '
                f'New names not in the baseline: {", ".join(fresh) or "(see --list)"}'
            )
            sys.exit(1)
        if count < threshold:
            print(
                f'note: the count dropped below the threshold — №466 should move '
                f'the threshold down to {count} in a follow-up naryad.'
            )
        return
    print(len(dups))


if __name__ == '__main__':
    main()
