#!/usr/bin/env python3
"""№463: the generative contour stop-list gate.

The manifest (docs/generative-contour-manifest.txt) lists the contour
files; the baseline (docs/generative-contour-manifest.baseline) pins
the manifest's SHA-256 and each file's LOC.

Fails when:
  (а) any contour file's LOC grew above its baseline line count
      (bug fixes WITHOUT growth are allowed — the gate tracks growth,
      not changes; shrinking is welcome and noted);
  (б) the manifest itself changed in any way (an extension, a removal,
      an edit) — the single exception is an owner-approved ADR-0178
      patch, which must be linked in the PR;
  a contour file is missing (deletion is also a manifest change).

Usage:
  generative_stop_list_gate.py --freeze   → (re)generate the baseline
  generative_stop_list_gate.py            → run the gate (CI)
"""
import hashlib
import re
import subprocess
import sys

ROOT = __file__.rsplit('/scripts/ci/', 1)[0]
MANIFEST = ROOT + '/docs/generative-contour-manifest.txt'
BASELINE = ROOT + '/docs/generative-contour-manifest.baseline'


def manifest_files() -> list:
    files = []
    for line in open(MANIFEST, encoding='utf-8'):
        line = line.rstrip('\n')
        if not line or line.lstrip().startswith('#'):
            continue
        files.append(line.strip())
    return files


def manifest_sha() -> str:
    return hashlib.sha256(open(MANIFEST, 'rb').read()).hexdigest()


def file_loc(path: str) -> int:
    out = subprocess.run(['wc', '-l', path], capture_output=True, text=True)
    return int(out.stdout.split()[0])


def compute() -> dict:
    files = manifest_files()
    per_file = {f: file_loc(f) for f in files}
    return {
        'sha': manifest_sha(),
        'per_file': per_file,
        'total': sum(per_file.values()),
    }


def freeze() -> None:
    data = compute()
    with open(BASELINE, 'w', encoding='utf-8') as f:
        f.write(f'# №463 baseline — generated by generative_stop_list_gate.py --freeze\n')
        f.write(f'# DO NOT EDIT by hand: the manifest + this file move ONLY via an owner-approved ADR-0178 patch.\n')
        f.write(f'manifest_sha256: {data["sha"]}\n')
        f.write(f'total_loc: {data["total"]}\n')
        for path, loc in data['per_file'].items():
            f.write(f'{path}: {loc}\n')
    print(f'baseline frozen: {len(data["per_file"])} files, total {data["total"]} LOC')


def gate() -> None:
    # (б) FIRST: any manifest edit is a stop-list change — check the SHA
    # before touching the listed files (a manifest that names a non-existent
    # file must fail here, not crash).
    sha, per_file, total = None, {}, None
    for line in open(BASELINE, encoding='utf-8'):
        m = re.match(r'manifest_sha256:\s*([0-9a-f]{64})', line)
        if m:
            sha = m.group(1)
            continue
        m = re.match(r'total_loc:\s*(\d+)', line)
        if m:
            total = int(m.group(1))
            continue
        m = re.match(r'(\S+):\s*(\d+)$', line)
        if m:
            per_file[m.group(1)] = int(m.group(2))
    current_sha = manifest_sha()
    if sha != current_sha:
        print(
            '::error::(б) the generative contour MANIFEST changed — extending, '
            'shrinking or editing it requires an owner-approved ADR-0178 patch '
            '(naryad №463 §Границы). Link the ADR patch in the PR. '
            f'(baseline sha {sha[:12]}…, current {current_sha[:12]}…)'
        )
        sys.exit(1)
    data = compute()
    failures = []
    shrunk = []
    for path, base_loc in per_file.items():
        if path not in data['per_file']:
            failures.append(f'{path}: REMOVED from the tree (a manifest change is required to remove files)')
            continue
        if data['per_file'][path] > base_loc:
            failures.append(f'{path}: {base_loc} → {data["per_file"][path]} LOC (+{data["per_file"][path] - base_loc})')
        elif data['per_file'][path] < base_loc:
            shrunk.append(f'{path}: {base_loc} → {data["per_file"][path]}')
    print(f'generative contour: {len(per_file)} files, {total} LOC baseline, {data["total"]} LOC now')
    if shrunk:
        print('note: the contour SHRANK (welcome — record it in the wave report):')
        for s in shrunk:
            print(f'  {s}')
    if failures:
        print(
            '::error::(а) the generative contour GREW beyond the baseline '
            '(the owner\u2019s stop-list, gh#680 decision 5-B; the preconditions '
            'of any extension are open: №456/№457, the Secret-in-embedding '
            'runtime check, the call budget):'
        )
        for f_ in failures:
            print(f'  {f_}')
        sys.exit(1)
    print('✓ the generative contour does not grow')


if __name__ == '__main__':
    if '--freeze' in sys.argv:
        freeze()
    else:
        gate()
