// ── mlogpkg: METALOGOS Package Manager ──────────────────────────────────
//
// `mlogpkg init`              — creates mlog.toml (name, version, dependencies)
// `mlogpkg add <pkg>`         — adds a dependency to mlog.toml (resolves
//                                transitively, detects version conflicts)
// `mlogpkg build`             — resolves full dependency graph, writes
//                                mlogpkg.lock, runs semantic check on sources
// `mlogpkg audit`             — checks dependencies against local advisory DB
//                                (Наряд №198, Block 2 — limited scope)
// `mlogpkg info`              — show current project info
//
// Local registry: packages stored in ~/.mlog/registry/<pkg-name>/
// No remote server at this phase.
//
// Наряд №198 — full dependency graph resolution + lockfile + audit:
//   - resolve_dependencies() now walks the full transitive graph (not just
//     direct deps), detects version conflicts, detects cycles
//   - mlogpkg.lock is the new lockfile name (was mlog.lock); it's a TOML
//     file with a `version = 1` header and `[[package]]` entries sorted
//     alphabetically by name for determinism
//   - audit reads a local advisory DB (mlogpkg/advisory-db.toml bundled
//     with the binary, overrideable via MLOGPKG_ADVISORY_DB env var)
//
// Limitation (Block 2): the advisory DB is a manually-maintained local
// file, not an integration with an external CVE database. This is
// explicitly documented in README and in the advisory-db.toml header.

use clap::Parser;
use std::collections::{BTreeMap, HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Parser, Debug)]
#[command(
    name = "mlogpkg",
    about = "METALOGOS package manager",
    // Note: do NOT use `version`/`propagate_version` here — the `Add` subcommand
    // has a positional argument named `version`, which conflicts with clap's
    // auto-generated `--version` flag. Version is reported via cargo metadata
    // instead (cargo build embeds it).
    disable_version_flag = true,
    disable_help_subcommand = false
)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(clap::Subcommand, Debug)]
enum Commands {
    /// Initialize a new METALOGOS project (creates mlog.toml)
    Init {
        /// Project name (defaults to directory name)
        #[arg(short, long)]
        name: Option<String>,
    },
    /// Add a dependency to mlog.toml
    Add {
        /// Package name to add as dependency
        pkg: String,
        /// Optional version constraint (e.g. "0.3.0")
        version: Option<String>,
    },
    /// Resolve dependencies, write mlogpkg.lock, run semantic check on sources
    Build,
    /// Show current project info
    Info,
    /// Audit dependencies against the local advisory database (Наряд №198)
    Audit,
}

/// mlog.toml manifest structure.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
struct Manifest {
    package: Package,
    #[serde(default)]
    dependencies: HashMap<String, String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
struct Package {
    name: String,
    version: String,
    #[serde(default)]
    edition: String,
}

impl Default for Package {
    fn default() -> Self {
        Self {
            name: "untitled".to_string(),
            version: "0.1.0".to_string(),
            edition: "2024".to_string(),
        }
    }
}

// ── Lockfile (Наряд №198 Block 1) ──────────────────────────────────────
//
// TOML format, deterministic (packages sorted alphabetically).
// Same mlog.toml → same mlogpkg.lock byte-for-byte.
//
// Example:
//
//   # This file is automatically generated by mlogpkg.
//   # Do not edit manually — run `mlogpkg build` to regenerate.
//   version = 1
//
//   [[package]]
//   name = "foo"
//   version = "1.0.0"
//   source = "registry"
//
//   [[package]]
//   name = "bar"
//   version = "0.5.0"
//   source = "registry"

const LOCKFILE_VERSION: u32 = 1;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
struct LockFile {
    version: u32,
    /// Array-of-tables `[[package]]` — sorted alphabetically for determinism.
    /// Same mlog.toml → same lockfile byte-for-byte.
    #[serde(default)]
    package: Vec<LockedPkg>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
struct LockedPkg {
    name: String,
    version: String,
    source: String,
}

impl LockFile {
    fn new() -> Self {
        Self {
            version: LOCKFILE_VERSION,
            package: Vec::new(),
        }
    }

    fn from_resolved(resolved: &ResolvedGraph) -> Self {
        let mut lock = Self::new();
        for (name, pkg) in &resolved.packages {
            lock.package.push(LockedPkg {
                name: name.clone(),
                version: pkg.version.clone(),
                source: pkg.source.clone(),
            });
        }
        // BTreeMap iteration is already sorted, but sort again defensively
        // in case the source iteration order changes.
        lock.package.sort_by(|a, b| a.name.cmp(&b.name));
        lock
    }

    fn write_to(&self, path: &Path) -> Result<(), String> {
        let mut toml_str = toml::to_string_pretty(self)
            .map_err(|e| format!("failed to serialize lockfile: {}", e))?;
        let header = "# This file is automatically generated by mlogpkg.\n\
                      # Do not edit manually — run `mlogpkg build` to regenerate.\n";
        toml_str = format!("{}{}", header, toml_str);
        fs::write(path, toml_str).map_err(|e| format!("failed to write {:?}: {}", path, e))
    }

    fn read(path: &Path) -> Result<Self, String> {
        let content =
            fs::read_to_string(path).map_err(|e| format!("failed to read {:?}: {}", path, e))?;
        toml::from_str(&content).map_err(|e| format!("failed to parse {:?}: {}", path, e))
    }
}

// ── Dependency graph resolution (Наряд №198 Block 1) ───────────────────
//
// Resolves the full transitive closure of dependencies, detecting:
//   - Missing packages (not in local registry)
//   - Version conflicts (two packages require different versions of the
//     same transitive dep — the spec says "explicit, understandable
//     error", NOT silent resolution)
//   - Cycles (A→B→A)

/// A resolved package in the dependency graph.
#[derive(Debug, Clone)]
struct ResolvedPkg {
    version: String,
    source: String,
    /// Names of packages that depend on this one (for error reporting).
    required_by: Vec<String>,
}

/// The full resolved dependency graph.
#[derive(Debug, Clone)]
struct ResolvedGraph {
    /// BTreeMap for deterministic ordering (lockfile determinism).
    packages: BTreeMap<String, ResolvedPkg>,
}

/// Errors that can occur during dependency resolution.
#[derive(Debug)]
enum ResolveError {
    /// Package not found in local registry.
    PackageNotFound { name: String, required_by: String },
    /// Two packages require different versions of the same transitive dep.
    VersionConflict {
        name: String,
        existing_version: String,
        existing_required_by: String,
        new_version: String,
        new_required_by: String,
    },
    /// Dependency cycle detected (A→B→A).
    Cycle { chain: Vec<String> },
}

impl std::fmt::Display for ResolveError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ResolveError::PackageNotFound { name, required_by } => write!(
                f,
                "package '{}' (required by '{}') not found in local registry",
                name, required_by
            ),
            ResolveError::VersionConflict {
                name,
                existing_version,
                existing_required_by,
                new_version,
                new_required_by,
            } => write!(
                f,
                "version conflict for '{}': '{}' requires version '{}', but '{}' already requires version '{}' \
                 (mlogpkg v1 does not support multiple concurrent versions of the same package)",
                name, new_required_by, new_version, existing_required_by, existing_version
            ),
            ResolveError::Cycle { chain } => {
                write!(f, "dependency cycle detected: {}", chain.join(" -> "))
            }
        }
    }
}

/// Resolve the full transitive dependency graph starting from a manifest.
///
/// Walks the dependency tree depth-first, accumulating resolved packages
/// into a BTreeMap. When a package is encountered a second time, its version
/// is compared to the previously resolved version — mismatch → VersionConflict.
/// Cycles are detected via the "currently resolving" stack.
fn resolve_graph(manifest: &Manifest, registry: &Path) -> Result<ResolvedGraph, ResolveError> {
    let mut resolved: BTreeMap<String, ResolvedPkg> = BTreeMap::new();
    let mut resolving: HashSet<String> = HashSet::new();
    let mut stack: Vec<String> = Vec::new();

    let root_name = manifest.package.name.clone();
    for (dep_name, dep_version) in &manifest.dependencies {
        resolve_recursive(
            dep_name,
            dep_version,
            &root_name,
            registry,
            &mut resolved,
            &mut resolving,
            &mut stack,
        )?;
    }

    Ok(ResolvedGraph { packages: resolved })
}

fn resolve_recursive(
    name: &str,
    version_req: &str,
    required_by: &str,
    registry: &Path,
    resolved: &mut BTreeMap<String, ResolvedPkg>,
    resolving: &mut HashSet<String>,
    stack: &mut Vec<String>,
) -> Result<(), ResolveError> {
    // Cycle detection: if this package is already in the active resolution
    // stack, we have a cycle.
    if resolving.contains(name) {
        let mut chain: Vec<String> = stack
            .iter()
            .skip_while(|n| n.as_str() != name)
            .cloned()
            .collect();
        chain.push(name.to_string());
        return Err(ResolveError::Cycle { chain });
    }

    // Already resolved? Check version matches.
    if let Some(existing) = resolved.get(name) {
        if existing.version != version_req {
            return Err(ResolveError::VersionConflict {
                name: name.to_string(),
                existing_version: existing.version.clone(),
                existing_required_by: existing.required_by.first().cloned().unwrap_or_default(),
                new_version: version_req.to_string(),
                new_required_by: required_by.to_string(),
            });
        }
        // Same version — record the additional requirer, then return (already resolved).
        resolved
            .get_mut(name)
            .unwrap()
            .required_by
            .push(required_by.to_string());
        return Ok(());
    }

    // Find package in registry.
    let pkg_dir = registry.join(name);
    if !pkg_dir.exists() {
        return Err(ResolveError::PackageNotFound {
            name: name.to_string(),
            required_by: required_by.to_string(),
        });
    }

    let pkg_manifest = read_manifest_optional(&pkg_dir.join("mlog.toml")).ok_or_else(|| {
        ResolveError::PackageNotFound {
            name: name.to_string(),
            required_by: required_by.to_string(),
        }
    })?;

    // Verify the package's actual version matches the requested version_req.
    // For first version: exact match only (no semver ranges).
    if pkg_manifest.package.version != version_req {
        return Err(ResolveError::VersionConflict {
            name: name.to_string(),
            existing_version: pkg_manifest.package.version.clone(),
            existing_required_by: format!("(registry:{})", name),
            new_version: version_req.to_string(),
            new_required_by: required_by.to_string(),
        });
    }

    // Mark as currently resolving (for cycle detection).
    resolving.insert(name.to_string());
    stack.push(name.to_string());

    // Recursively resolve this package's dependencies.
    for (trans_name, trans_version) in &pkg_manifest.dependencies {
        resolve_recursive(
            trans_name,
            trans_version,
            name,
            registry,
            resolved,
            resolving,
            stack,
        )?;
    }

    stack.pop();
    resolving.remove(name);

    // Insert into resolved map.
    resolved.insert(
        name.to_string(),
        ResolvedPkg {
            version: version_req.to_string(),
            source: "registry".to_string(),
            required_by: vec![required_by.to_string()],
        },
    );

    Ok(())
}

// ── Advisory DB (Наряд №198 Block 2) ───────────────────────────────────
//
// Local, manually-maintained advisory database in TOML format.
//
// Limitation: this is NOT an integration with an external CVE database
// (RUSTSEC, NVD, GitHub Advisory DB, etc.). It is a local file bundled
// with the mlogpkg binary, updated manually as vulnerabilities are
// discovered. The limitation is explicitly documented in README and in
// the advisory-db.toml file header.
//
// The DB path can be overridden via the MLOGPKG_ADVISORY_DB env var —
// useful for tests and for projects that want to extend the bundled DB
// with project-specific advisories.

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
struct AdvisoryDb {
    #[serde(default)]
    advisory: Vec<Advisory>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
struct Advisory {
    /// Stable advisory ID (e.g. "MLOG-001").
    id: String,
    /// Affected package name (must match a dependency name in mlog.toml).
    package: String,
    /// Affected version (exact match — no semver ranges in v1).
    version: String,
    /// Severity: "low" | "medium" | "high" | "critical".
    severity: String,
    /// Short title.
    title: String,
    /// Longer description.
    #[serde(default)]
    description: String,
    /// Optional URL for more details.
    #[serde(default)]
    url: String,
}

impl AdvisoryDb {
    /// Load the advisory DB. Path resolution order:
    ///   1. MLOGPKG_ADVISORY_DB env var (if set)
    ///   2. bundled file at <mlogpkg source dir>/advisory-db.toml
    ///   3. ~/.mlog/advisory-db.toml (user override)
    ///   4. empty DB if none found (audit reports 0 advisories, with a warning)
    fn load() -> (Self, PathBuf) {
        if let Ok(path) = std::env::var("MLOGPKG_ADVISORY_DB") {
            let p = PathBuf::from(&path);
            if let Ok(content) = fs::read_to_string(&p) {
                if let Ok(db) = toml::from_str::<AdvisoryDb>(&content) {
                    return (db, p);
                }
            }
            return (Self::empty(), p);
        }

        // Try ~/.mlog/advisory-db.toml (user override of bundled DB).
        if let Some(home) = std::env::var_os("HOME") {
            let user_db = PathBuf::from(home).join(".mlog/advisory-db.toml");
            if user_db.exists() {
                if let Ok(content) = fs::read_to_string(&user_db) {
                    if let Ok(db) = toml::from_str::<AdvisoryDb>(&content) {
                        return (db, user_db);
                    }
                }
            }
        }

        (Self::empty(), PathBuf::new())
    }

    fn empty() -> Self {
        Self { advisory: vec![] }
    }

    /// Check if any advisory matches the given (name, version) pair.
    fn find_advisories(&self, name: &str, version: &str) -> Vec<&Advisory> {
        self.advisory
            .iter()
            .filter(|a| a.package == name && a.version == version)
            .collect()
    }
}

// ── Command implementations ───────────────────────────────────────────

fn main() {
    let cli = Cli::parse();

    match cli.command {
        Commands::Init { name } => cmd_init(name),
        Commands::Add { pkg, version } => cmd_add(&pkg, version.as_deref()),
        Commands::Build => cmd_build(),
        Commands::Info => cmd_info(),
        Commands::Audit => cmd_audit(),
    }
}

/// `mlogpkg init [name]` — create mlog.toml in current directory.
fn cmd_init(name: Option<String>) {
    let manifest_path = PathBuf::from("mlog.toml");
    if manifest_path.exists() {
        eprintln!("error: mlog.toml already exists");
        std::process::exit(1);
    }

    let project_name = name.unwrap_or_else(|| {
        std::env::current_dir()
            .ok()
            .and_then(|p| p.file_name().map(|n| n.to_string_lossy().to_string()))
            .unwrap_or_else(|| "untitled".to_string())
    });

    let manifest = Manifest {
        package: Package {
            name: project_name,
            version: "0.1.0".to_string(),
            edition: "2024".to_string(),
        },
        dependencies: HashMap::new(),
    };

    let toml_str = toml::to_string_pretty(&manifest).expect("failed to serialize manifest");
    fs::write(&manifest_path, &toml_str).expect("failed to write mlog.toml");

    // Also create src/ and a minimal entry.mlog
    fs::create_dir_all("src").ok();
    let entry = "entity greeting: String = \"Hello from mlogpkg!\"\nflow Main { input: String = greeting -> output }\n";
    fs::write("src/main.mlog", entry).ok();

    println!("Created mlog.toml for project");
    println!("  name: {}", manifest.package.name);
    println!("  version: {}", manifest.package.version);
    println!("  entry: src/main.mlog");
}

/// `mlogpkg add <pkg> [version]` — add dependency to mlog.toml.
///
/// Наряд №198: now resolves the full transitive graph BEFORE writing
/// mlog.toml, so version conflicts are reported at `add` time (not
/// deferred to `build`). If a conflict is detected, mlog.toml is left
/// unchanged and an explicit error is printed.
fn cmd_add(pkg: &str, version: Option<&str>) {
    let manifest_path = PathBuf::from("mlog.toml");
    if !manifest_path.exists() {
        eprintln!("error: mlog.toml not found. Run 'mlogpkg init' first.");
        std::process::exit(1);
    }

    // Check if package exists in local registry.
    let registry_dir = registry_dir();
    let pkg_dir = registry_dir.join(pkg);
    if !pkg_dir.exists() {
        eprintln!(
            "error: package '{}' not found in local registry ({})",
            pkg,
            registry_dir.display()
        );
        eprintln!("  Install packages manually to: {}", registry_dir.display());
        std::process::exit(1);
    }

    // Read the package's manifest to get its version.
    let pkg_manifest_path = pkg_dir.join("mlog.toml");
    let pkg_manifest = read_manifest(&pkg_manifest_path);
    let resolved_version = match version {
        Some(v) => v.to_string(),
        None => pkg_manifest.package.version.clone(),
    };

    // Verify the requested version matches the package's actual version.
    if pkg_manifest.package.version != resolved_version {
        eprintln!(
            "error: version mismatch for '{}': requested '{}', but registry has '{}'",
            pkg, resolved_version, pkg_manifest.package.version
        );
        std::process::exit(1);
    }

    // Read current manifest, add the dep, then resolve the full graph
    // to detect conflicts BEFORE writing mlog.toml.
    let mut manifest = read_manifest(&manifest_path);
    let prev = manifest
        .dependencies
        .insert(pkg.to_string(), resolved_version.clone());

    // Pre-flight: resolve the full graph with this new dep included.
    // If it fails, restore the previous state of dependencies and exit.
    match resolve_graph(&manifest, &registry_dir) {
        Ok(graph) => {
            println!(
                "Resolved {} packages (including transitive):",
                graph.packages.len()
            );
            for (name, p) in &graph.packages {
                println!("  {} = {}", name, p.version);
            }
        }
        Err(e) => {
            // Restore previous state.
            match &prev {
                Some(old) => {
                    manifest.dependencies.insert(pkg.to_string(), old.clone());
                }
                None => {
                    manifest.dependencies.remove(pkg);
                }
            }
            eprintln!("error: cannot add '{}': {}", pkg, e);
            std::process::exit(1);
        }
    }

    if let Some(old) = prev {
        println!("Updated dependency: {} (was {})", pkg, old);
    } else {
        println!("Added dependency: {} = {}", pkg, resolved_version);
    }

    write_manifest(&manifest_path, &manifest);
    println!("Dependencies:");
    for (dep_name, dep_ver) in &manifest.dependencies {
        println!("  {} = {}", dep_name, dep_ver);
    }
}

/// `mlogpkg build` — resolve dependencies, write mlogpkg.lock, run semantic check.
fn cmd_build() {
    let manifest_path = PathBuf::from("mlog.toml");
    if !manifest_path.exists() {
        eprintln!("error: mlog.toml not found. Run 'mlogpkg init' first.");
        std::process::exit(1);
    }

    let manifest = read_manifest(&manifest_path);
    println!(
        "Building {} v{}",
        manifest.package.name, manifest.package.version
    );

    // 1. Find entry point.
    let entry = find_entry_point();
    println!("  entry: {}", entry.display());

    // 2. Resolve full dependency graph (transitive closure + conflict detection).
    let registry = registry_dir();
    let resolved = match resolve_graph(&manifest, &registry) {
        Ok(g) => g,
        Err(e) => {
            eprintln!("error: dependency resolution failed: {}", e);
            std::process::exit(1);
        }
    };
    println!("  dependencies resolved: {}", resolved.packages.len());
    for (name, p) in &resolved.packages {
        println!("    {} = {}", name, p.version);
    }

    // 3. Collect all source files.
    let mut all_sources = Vec::new();
    collect_sources(PathBuf::from("src"), &mut all_sources);
    println!("  source files: {}", all_sources.len());

    // 4. Semantic check each source file.
    let mut errors = 0;
    for src in &all_sources {
        match fs::read_to_string(src) {
            Ok(source) => match metalogos::check_program(&source) {
                Ok(result) => {
                    if !result.is_ok() {
                        println!("  ERRORS in {}: {}", src.display(), result.format());
                        errors += result.error_count();
                    }
                }
                Err(e) => {
                    println!("  ERROR in {}: {}", src.display(), e);
                    errors += 1;
                }
            },
            Err(e) => {
                println!("  ERROR: cannot read {}: {}", src.display(), e);
                errors += 1;
            }
        }
    }

    // 5. Write lockfile (mlogpkg.lock — Наряд №198).
    let lock = LockFile::from_resolved(&resolved);
    let lock_path = PathBuf::from("mlogpkg.lock");
    if let Err(e) = lock.write_to(&lock_path) {
        eprintln!("  warning: failed to write lockfile: {}", e);
    } else {
        println!("  lockfile: {}", lock_path.display());
    }

    if errors == 0 {
        println!(
            "Build OK: {} source files checked, 0 errors.",
            all_sources.len()
        );
    } else {
        println!("Build FAILED: {} error(s).", errors);
        std::process::exit(1);
    }
}

/// `mlogpkg info` — show project info.
fn cmd_info() {
    let manifest_path = PathBuf::from("mlog.toml");
    if !manifest_path.exists() {
        println!("No mlog.toml found. Run 'mlogpkg init' first.");
        return;
    }
    let manifest = read_manifest(&manifest_path);
    println!(
        "Project: {} v{}",
        manifest.package.name, manifest.package.version
    );
    println!("Edition: {}", manifest.package.edition);
    if manifest.dependencies.is_empty() {
        println!("Dependencies: (none)");
    } else {
        println!("Dependencies:");
        for (name, ver) in &manifest.dependencies {
            println!("  {} = {}", name, ver);
        }
    }
    let entry = find_entry_point();
    println!("Entry: {}", entry.display());
    let registry = registry_dir();
    println!("Registry: {}", registry.display());

    // Show lockfile status.
    let lock_path = PathBuf::from("mlogpkg.lock");
    if lock_path.exists() {
        match LockFile::read(&lock_path) {
            Ok(lock) => {
                println!(
                    "Lockfile: {} (v{}, {} packages)",
                    lock_path.display(),
                    lock.version,
                    lock.package.len()
                );
            }
            Err(e) => {
                println!("Lockfile: {} (parse error: {})", lock_path.display(), e);
            }
        }
    } else {
        println!("Lockfile: (none — run 'mlogpkg build' to generate)");
    }
}

/// `mlogpkg audit` — check dependencies against local advisory DB (Наряд №198 Block 2).
///
/// Limitation: this is a LOCAL, MANUALLY-MAINTAINED advisory database, not
/// an integration with an external CVE database. The DB is bundled with
/// mlogpkg and can be overridden via MLOGPKG_ADVISORY_DB env var. This
/// limitation is explicitly documented in README and printed to the user
/// when audit runs.
fn cmd_audit() {
    let manifest_path = PathBuf::from("mlog.toml");
    if !manifest_path.exists() {
        eprintln!("error: mlog.toml not found. Run 'mlogpkg init' first.");
        std::process::exit(1);
    }

    let manifest = read_manifest(&manifest_path);

    // Resolve the full dependency graph (needed to know ALL transitive deps).
    let registry = registry_dir();
    let resolved = match resolve_graph(&manifest, &registry) {
        Ok(g) => g,
        Err(e) => {
            eprintln!("error: dependency resolution failed: {}", e);
            std::process::exit(1);
        }
    };

    // Load advisory DB.
    let (db, db_path) = AdvisoryDb::load();

    println!(
        "Auditing {} packages against advisory DB:",
        resolved.packages.len()
    );
    if db_path.as_os_str().is_empty() {
        println!("  (no advisory DB found — using empty DB; 0 advisories will be reported)");
        println!("  set MLOGPKG_ADVISORY_DB env var or create ~/.mlog/advisory-db.toml");
    } else {
        println!("  DB: {}", db_path.display());
    }
    println!("  advisories in DB: {}", db.advisory.len());
    println!();
    println!("Note: this is a LOCAL, manually-maintained advisory database.");
    println!("      It is NOT an integration with an external CVE database.");
    println!("      For real-world security auditing, supplement with external tools.");
    println!();

    // Check each resolved package against the DB.
    let mut found_count = 0;
    for (name, pkg) in &resolved.packages {
        let advisories = db.find_advisories(name, &pkg.version);
        if advisories.is_empty() {
            continue;
        }
        for adv in advisories {
            println!(
                "[{}] {} v{} — {} ({})",
                adv.severity.to_uppercase(),
                name,
                pkg.version,
                adv.id,
                adv.title
            );
            if !adv.description.is_empty() {
                println!("  {}", adv.description);
            }
            if !adv.url.is_empty() {
                println!("  see: {}", adv.url);
            }
            found_count += 1;
        }
    }

    if found_count == 0 {
        println!("No known advisories match your dependencies.");
        std::process::exit(0);
    } else {
        println!();
        println!("Found {} advisory/advisories.", found_count);
        std::process::exit(1);
    }
}

// ── Helper functions ───────────────────────────────────────────────────

fn registry_dir() -> PathBuf {
    // MLOGPKG_REGISTRY env var override (useful for tests).
    if let Ok(p) = std::env::var("MLOGPKG_REGISTRY") {
        return PathBuf::from(p);
    }
    std::env::var("HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from("."))
        .join(".mlog")
        .join("registry")
}

fn read_manifest(path: &Path) -> Manifest {
    let content = fs::read_to_string(path).unwrap_or_else(|_| panic!("failed to read {:?}", path));
    toml::from_str(&content).unwrap_or_else(|_| panic!("failed to parse {:?}", path))
}

fn read_manifest_optional(path: &Path) -> Option<Manifest> {
    let content = fs::read_to_string(path).ok()?;
    toml::from_str(&content).ok()
}

fn write_manifest(path: &Path, manifest: &Manifest) {
    let toml_str = toml::to_string_pretty(manifest).expect("failed to serialize manifest");
    fs::write(path, &toml_str).unwrap_or_else(|_| panic!("failed to write {:?}", path));
}

fn find_entry_point() -> PathBuf {
    let candidates = [PathBuf::from("src/main.mlog"), PathBuf::from("main.mlog")];
    for c in &candidates {
        if c.exists() {
            return c.clone();
        }
    }
    PathBuf::from("src/main.mlog")
}

fn collect_sources(dir: PathBuf, files: &mut Vec<PathBuf>) {
    if let Ok(entries) = fs::read_dir(&dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                collect_sources(path, files);
            } else if path.extension().map(|e| e == "mlog").unwrap_or(false) {
                files.push(path);
            }
        }
    }
}

// ── Tests ──────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn setup_test_registry(name: &str) -> (tempfile::TempDir, PathBuf) {
        let dir = tempfile::TempDir::new().unwrap();
        let registry = dir.path().join(".mlog").join("registry");
        let _ = name; // for log identification if needed
        fs::create_dir_all(&registry).unwrap();
        (dir, registry)
    }

    fn write_pkg_to_registry(registry: &Path, name: &str, version: &str, deps: &[(&str, &str)]) {
        let pkg_dir = registry.join(name);
        fs::create_dir_all(&pkg_dir).unwrap();
        let mut deps_map = HashMap::new();
        for (d, v) in deps {
            deps_map.insert(d.to_string(), v.to_string());
        }
        let manifest = Manifest {
            package: Package {
                name: name.to_string(),
                version: version.to_string(),
                edition: "2024".to_string(),
            },
            dependencies: deps_map,
        };
        let toml_str = toml::to_string_pretty(&manifest).unwrap();
        fs::write(pkg_dir.join("mlog.toml"), toml_str).unwrap();
        // Also create a minimal source file so build doesn't error.
        fs::create_dir_all(pkg_dir.join("src")).unwrap();
        fs::write(
            pkg_dir.join("src/main.mlog"),
            "entity v: String = \"\"\nflow Main { input: String = v -> output }\n",
        )
        .unwrap();
    }

    #[test]
    fn test_resolve_graph_no_deps() {
        let (_dir, registry) = setup_test_registry("resolve_no_deps");
        let manifest = Manifest {
            package: Package::default(),
            dependencies: HashMap::new(),
        };
        let graph = resolve_graph(&manifest, &registry).unwrap();
        assert!(graph.packages.is_empty());
    }

    #[test]
    fn test_resolve_graph_direct_deps() {
        let (_dir, registry) = setup_test_registry("resolve_direct");
        write_pkg_to_registry(&registry, "foo", "1.0.0", &[]);
        write_pkg_to_registry(&registry, "bar", "0.5.0", &[]);

        let mut deps = HashMap::new();
        deps.insert("foo".to_string(), "1.0.0".to_string());
        deps.insert("bar".to_string(), "0.5.0".to_string());
        let manifest = Manifest {
            package: Package::default(),
            dependencies: deps,
        };

        let graph = resolve_graph(&manifest, &registry).unwrap();
        assert_eq!(graph.packages.len(), 2);
        assert_eq!(graph.packages["foo"].version, "1.0.0");
        assert_eq!(graph.packages["bar"].version, "0.5.0");
    }

    #[test]
    fn test_resolve_graph_transitive_deps() {
        let (_dir, registry) = setup_test_registry("resolve_transitive");
        // app -> lib_a (1.0.0) -> lib_b (2.0.0)
        write_pkg_to_registry(&registry, "lib_b", "2.0.0", &[]);
        write_pkg_to_registry(&registry, "lib_a", "1.0.0", &[("lib_b", "2.0.0")]);

        let mut deps = HashMap::new();
        deps.insert("lib_a".to_string(), "1.0.0".to_string());
        let manifest = Manifest {
            package: Package::default(),
            dependencies: deps,
        };

        let graph = resolve_graph(&manifest, &registry).unwrap();
        assert_eq!(graph.packages.len(), 2);
        assert!(graph.packages.contains_key("lib_a"));
        assert!(graph.packages.contains_key("lib_b"));
    }

    #[test]
    fn test_resolve_graph_version_conflict() {
        let (_dir, registry) = setup_test_registry("resolve_conflict");
        // app -> pkg_a (1.0.0) -> shared (1.0.0)
        // app -> pkg_b (1.0.0) -> shared (2.0.0)
        // conflict: shared must be both 1.0.0 and 2.0.0
        write_pkg_to_registry(&registry, "shared", "1.0.0", &[]);
        // We need shared 2.0.0 too — but registry only has one version per name.
        // For the test, we trick: pkg_b requires shared 2.0.0, but registry
        // has shared 1.0.0. resolve_graph will fail with VersionConflict
        // because the requested version (2.0.0) doesn't match the resolved
        // version (1.0.0).
        write_pkg_to_registry(&registry, "pkg_a", "1.0.0", &[("shared", "1.0.0")]);
        write_pkg_to_registry(&registry, "pkg_b", "1.0.0", &[("shared", "2.0.0")]);

        let mut deps = HashMap::new();
        deps.insert("pkg_a".to_string(), "1.0.0".to_string());
        deps.insert("pkg_b".to_string(), "1.0.0".to_string());
        let manifest = Manifest {
            package: Package::default(),
            dependencies: deps,
        };

        let err = resolve_graph(&manifest, &registry).unwrap_err();
        match err {
            ResolveError::VersionConflict { name, .. } => {
                assert_eq!(name, "shared");
            }
            other => panic!("expected VersionConflict, got: {:?}", other),
        }
    }

    #[test]
    fn test_resolve_graph_cycle_detection() {
        let (_dir, registry) = setup_test_registry("resolve_cycle");
        // a -> b -> a (cycle)
        write_pkg_to_registry(&registry, "a", "1.0.0", &[("b", "1.0.0")]);
        write_pkg_to_registry(&registry, "b", "1.0.0", &[("a", "1.0.0")]);

        let mut deps = HashMap::new();
        deps.insert("a".to_string(), "1.0.0".to_string());
        let manifest = Manifest {
            package: Package::default(),
            dependencies: deps,
        };

        let err = resolve_graph(&manifest, &registry).unwrap_err();
        match err {
            ResolveError::Cycle { chain } => {
                assert!(chain.iter().any(|n| n == "a"));
                assert!(chain.iter().any(|n| n == "b"));
            }
            other => panic!("expected Cycle, got: {:?}", other),
        }
    }

    #[test]
    fn test_resolve_graph_missing_package() {
        let (_dir, registry) = setup_test_registry("resolve_missing");
        let mut deps = HashMap::new();
        deps.insert("nonexistent".to_string(), "1.0.0".to_string());
        let manifest = Manifest {
            package: Package::default(),
            dependencies: deps,
        };

        let err = resolve_graph(&manifest, &registry).unwrap_err();
        match err {
            ResolveError::PackageNotFound { name, .. } => {
                assert_eq!(name, "nonexistent");
            }
            other => panic!("expected PackageNotFound, got: {:?}", other),
        }
    }

    #[test]
    fn test_lockfile_determinism() {
        let (_dir, registry) = setup_test_registry("lockfile_det");
        write_pkg_to_registry(&registry, "zeta", "1.0.0", &[]);
        write_pkg_to_registry(&registry, "alpha", "1.0.0", &[]);
        write_pkg_to_registry(&registry, "mid", "1.0.0", &[]);

        let mut deps = HashMap::new();
        deps.insert("zeta".to_string(), "1.0.0".to_string());
        deps.insert("alpha".to_string(), "1.0.0".to_string());
        deps.insert("mid".to_string(), "1.0.0".to_string());
        let manifest = Manifest {
            package: Package::default(),
            dependencies: deps,
        };

        let graph1 = resolve_graph(&manifest, &registry).unwrap();
        let lock1 = LockFile::from_resolved(&graph1);
        let graph2 = resolve_graph(&manifest, &registry).unwrap();
        let lock2 = LockFile::from_resolved(&graph2);

        let toml1 = toml::to_string_pretty(&lock1).unwrap();
        let toml2 = toml::to_string_pretty(&lock2).unwrap();
        assert_eq!(toml1, toml2, "lockfile must be deterministic");

        // Verify alphabetical ordering.
        let names: Vec<String> = lock1.package.iter().map(|p| p.name.clone()).collect();
        let mut sorted = names.clone();
        sorted.sort();
        assert_eq!(names, sorted, "packages must be sorted alphabetically");
    }

    #[test]
    fn test_advisory_db_find_advisories() {
        let db = AdvisoryDb {
            advisory: vec![Advisory {
                id: "MLOG-001".to_string(),
                package: "vuln-lib".to_string(),
                version: "1.2.0".to_string(),
                severity: "high".to_string(),
                title: "Test vulnerability".to_string(),
                description: "Test description".to_string(),
                url: String::new(),
            }],
        };

        // Match.
        let found = db.find_advisories("vuln-lib", "1.2.0");
        assert_eq!(found.len(), 1);
        assert_eq!(found[0].id, "MLOG-001");

        // No match — wrong version.
        let found = db.find_advisories("vuln-lib", "1.3.0");
        assert_eq!(found.len(), 0);

        // No match — wrong package.
        let found = db.find_advisories("safe-lib", "1.2.0");
        assert_eq!(found.len(), 0);
    }
}
